#!/usr/bin/env python
#######################
#  Coded by Mr.Doel   #
#  Malang Cyber Crew  #
#  doel@mc-crew.or.id #
#######################

import urllib2
from BeautifulSoup import  BeautifulSoup

html=urllib2.urlopen("http://cmyip.com/")
soup=BeautifulSoup(html)
clss='page-title'
for ip in soup.findAll('h1', attrs={'class': 'page-title'}):
    print ''.join(ip.findAll(text=True)).replace('Hide IP Address','').rstrip()

for detail in soup.findAll('h3', attrs={'class': clss}):
    print ''.join(detail.findAll(text=True)).replace('Whois','').replace('Detected User Agent','').replace('Weather','').replace('Hotel','').replace('Speed Test','').rstrip()
